@BASE_URL=http://localhost:5000
@TOKEN = {{login.response.body.user.token}}

### login
# @name login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345"
}

### get deserts
GET {{BASE_URL}}/desserts
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### post desert
POST {{BASE_URL}}/desserts
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Matcha Cake5",
  "price": 140,
  "category": "cake"
}

### delete deserts
DELETE  {{BASE_URL}}/desserts/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}